title: "My Research Website"
name: "Naemi Leo"
description: "Research, publications and teaching"

url: "https://n-leo.github.io/"
baseurl: "skills-github-pages"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author:
  name: "Naëmi Leo"
  avatar: "/assets/images/profile.jpg"  
  bio: "Senior Research Fellow"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: posts
    values:
      layout: single

  - scope:
      path: ""
    values:
      layout: single

markdown: kramdown

minimal_mistakes_skin: air
